import { useEffect, useMemo, useState } from "react";
import { demoSnapshot } from "./demo";
import type { Quadrant, SectorState, Snapshot } from "./types";

const labels: Record<Quadrant,string>={leading:"Leading",weakening:"Weakening",lagging:"Lagging",improving:"Improving"};
const descriptions: Record<Quadrant,string>={leading:"상대강세 · 모멘텀 우위",weakening:"상대강세 유지 · 둔화",lagging:"상대약세 · 모멘텀 약세",improving:"상대약세 · 모멘텀 회복"};
const tailChoices=[4,8,12,26];
const mark=<span className="atlas-mark" aria-hidden="true"/>;

function getBounds(sectors:SectorState[],tail:number){const v=sectors.flatMap(s=>s.trail.slice(-(tail+1)).flatMap(p=>[p.ratio,p.momentum]));return {min:Math.min(98,...v)-.45,max:Math.max(102,...v)+.45};}
function Canvas({sectors,active,onPick,tail}:{sectors:SectorState[];active:string|null;onPick:(ticker:string)=>void;tail:number}){const {min,max}=useMemo(()=>getBounds(sectors,tail),[sectors,tail]);const scale=(v:number)=>12+(v-min)/(max-min)*76;const center=scale(100);return <svg className="rrg-canvas" viewBox="0 0 100 100" role="img" aria-label="SPY 대비 주간 RRG-style 섹터 지도"><rect width="100" height="100" className="paper"/><rect x={center} y="8" width={92-center} height={92-center} className="q lead"/><rect x={center} y={center} width={92-center} height={92-center} className="q weak"/><rect x="8" y={center} width={center-8} height={92-center} className="q lag"/><rect x="8" y="8" width={center-8} height={center-8} className="q improve"/><line x1={center} x2={center} y1="8" y2="92" className="origin"/><line x1="8" x2="92" y1={100-center} y2={100-center} className="origin"/><text x="10" y="13" className="qlabel">IMPROVING</text><text x="90" y="13" textAnchor="end" className="qlabel">LEADING</text><text x="10" y="90" className="qlabel">LAGGING</text><text x="90" y="90" textAnchor="end" className="qlabel">WEAKENING</text>{sectors.map(s=>{const display=s.trail.slice(-(tail+1));const last=display.at(-1)!;const selected=active===s.ticker;return <g key={s.ticker} className={`sector ${s.quadrant} ${active&&!selected?"faded":""} ${selected?"selected":""}`} tabIndex={0} role="button" onClick={()=>onPick(s.ticker)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")onPick(s.ticker)}} aria-label={`${s.ticker}, ${labels[s.quadrant]}, Ratio ${s.ratio.toFixed(2)}, Momentum ${s.momentum.toFixed(2)}`}><path className="tail" d={display.map((p,i)=>`${i?"L":"M"}${scale(p.ratio)} ${100-scale(p.momentum)}`).join(" ")}/><circle className="dot" cx={scale(last.ratio)} cy={100-scale(last.momentum)} r={selected?2.55:1.7}/><text className="ticker" x={scale(last.ratio)+2.2} y={100-scale(last.momentum)-1.8}>{s.ticker}</text></g>})}<text x="50" y="98" textAnchor="middle" className="axis">RS-RATIO →</text><text x="3" y="50" textAnchor="middle" transform="rotate(-90 3 50)" className="axis">RS-MOMENTUM →</text></svg>}
function Detail({sector,snapshot}:{sector:SectorState;snapshot:Snapshot}){return <section className="detail"><div className="eyebrow">SELECTED SECTOR</div><div className="detail-title"><strong>{sector.ticker}</strong><span>{sector.name}</span></div><span className={`pill ${sector.quadrant}`}>{labels[sector.quadrant]}</span><p>{descriptions[sector.quadrant]}</p><dl><div><dt>Ratio</dt><dd>{sector.ratio.toFixed(2)}</dd></div><div><dt>Momentum</dt><dd>{sector.momentum.toFixed(2)}</dd></div><div><dt>Heading</dt><dd>{sector.heading_degrees?.toFixed(0)??"—"}°</dd></div><div><dt>Velocity</dt><dd>{sector.velocity?.toFixed(2)??"—"}</dd></div></dl><small>{snapshot.tail_weeks}주 기준 · {snapshot.as_of_week}</small></section>}
export default function App(){const [snapshot,setSnapshot]=useState<Snapshot|null>(import.meta.env.DEV?demoSnapshot:null);const [error,setError]=useState<string|null>(null);const [filter,setFilter]=useState<Quadrant|"all">("all");const [tail,setTail]=useState(12);const [active,setActive]=useState<string|null>(null);useEffect(()=>{fetch("./data/latest.json").then(r=>r.ok?r.json():Promise.reject(new Error("No published snapshot"))).then((v:Snapshot)=>setSnapshot(v)).catch((e:Error)=>{if(!import.meta.env.DEV)setError(e.message)});},[]);const visible=useMemo(()=>snapshot?.sectors.filter(s=>filter==="all"||s.quadrant===filter)??[],[snapshot,filter]);useEffect(()=>{if(!active&&visible[0])setActive(visible[0].ticker)},[visible,active]);const selected=(snapshot?.sectors??[]).find(s=>s.ticker===active)??visible[0];if(!snapshot)return <main className="empty">{mark}<h1>검증된 스냅샷을 기다리고 있습니다.</h1><p>{error??"새 주간 스냅샷이 발행되면 RRG 지도가 열립니다."}</p></main>;return <main className="shell"><header><div className="brand">{mark}<span>RRG / ATLAS</span></div><div className={`status ${snapshot.status}`}><b>{snapshot.status==="verified"?"VERIFIED":snapshot.status.toUpperCase()}</b><span>{snapshot.as_of_week}</span></div></header><section className="intro"><div className="eyebrow">US SECTORS · SPY RELATIVE</div><h1>이번 주, 상대강도는<br/><em>어디로 회전했는가.</em></h1><p>{snapshot.frequency} · {snapshot.price_basis.replaceAll("_"," ")} · RRG-style proxy v1</p></section>{import.meta.env.DEV&&<div className="fixture">LOCAL PREVIEW FIXTURE · 실제 시장 데이터가 아닙니다.</div>}<nav className="controls"><div className="filters">{(["all","leading","weakening","lagging","improving"]as const).map(v=><button className={filter===v?"active":""} key={v} onClick={()=>setFilter(v)}>{v==="all"?"All":labels[v]}</button>)}</div><div className="tails"><span>Tail</span>{tailChoices.map(v=><button className={tail===v?"active":""} key={v} onClick={()=>setTail(v)}>{v}</button>)}</div></nav><section className="layout"><div className="map"><Canvas sectors={visible} active={selected?.ticker??null} onPick={setActive} tail={tail}/><small>{visible.length} sectors shown · {tail}W display</small></div><aside>{selected&&<Detail sector={selected} snapshot={snapshot}/>}<section className="ledger"><div className="eyebrow">ROTATION LEDGER</div>{snapshot.sectors.map(s=><button className={`row ${s.ticker===selected?.ticker?"active":""}`} key={s.ticker} onClick={()=>setActive(s.ticker)}><i className={s.quadrant}/><strong>{s.ticker}</strong><span>{labels[s.quadrant]}</span><em>{s.ratio.toFixed(1)} / {s.momentum.toFixed(1)}</em></button>)}</section></aside></section>{selected&&<section className="mobile-detail"><Detail sector={selected} snapshot={snapshot}/></section>}<footer><span>Snapshot {snapshot.snapshot_id} · benchmark {snapshot.benchmark}</span><span>데이터 기준과 산식은 방법론에서 확인하세요.</span></footer></main>}

